<footer class="footer-bg">
    <div class="footer-container">
        <div class="nav-area">
            <nav class="nav-bar">
                <div>
                    <i class="fa-solid fa-computer"></i>
                    <a href="">Ordinateurs</a>
                </div>
                <div>
                    <i class="fa-solid fa-database"></i>
                    <a href="">Péripheriques & composants</a>
                </div>
                <div>
                    <i class="fa-solid fa-mobile-screen"></i>
                    <a href="">Téléphones</a>
                </div>
                <div>
                    <i class="fa-solid fa-stopwatch"></i>
                    <a href="">Objets connectés</a>
                </div>
            </nav>
        </div>

        <div class="footer-grid">
            <div class="payment">
                <p class="footer-title">Moyens de paiement</p>
                <img src="image/payment_.png"></img>
            </div>
            <div class="socials">
                <p class="footer-title">Sur les réseaux sociaux</p>
                <div class="logo-container">
                    <i class="fa-brands fa-facebook logo fb"></i>
                    <i class="fa-brands fa-instagram logo insta"></i>
                    <i class="fa-brands fa-twitter logo twit"></i>
                    <i class="fa-brands fa-linkedin logo linkdn"></i>
                </div>
            </div>
            <div class="about">
                <p class="footer-title">A propos</p>
                <a href="#">Qui sommes-nous ?</a>
                <a href="#">Nos services</a>
                <a href="#">Contactez-nous</a>
            </div>
            <div class="about2">
                <p class="footer-title">A propos</p>
                <a href="#">Plan du site</a>
                <a href="#">Foire Aux Questions</a>
                <a href="#">Conditions générales de vente</a>
                <a href="#">Informations légales</a>
            </div>
            <div class="copyright">
                <img src="image/logo-3wa.png"></img>
                <p>Cet exercice de <span class="underline">3W Academy</span> est mis à disposition <span class="underline">pour l'usage personnel des étudiants. Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International. </span>Les
                    autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr">contact@3wa.fr</a>.<br>Maquette réalisée par <span class="underline">Stephane Pereck</span>.</p>
            </div>
        </div>

    </div>
</footer>