<header>

    <div class="header-container">

        <div class="accessibility-container">
            <div>
                <p>Options d'affichage / accessibilité</p>
            </div>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <p>Thème :</p>
                </li>
                <li class="list-inline-item"><a href="">sombre</a></li>
                <li class="list-inline-item"><a href="">contrasté</a></li>
                <li class="list-inline-item"><a href="">clair</a></li>
            </ul>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <p>Interlignage :</p>
                </li>
                <li class="list-inline-item"><a href="">simple</a></li>
                <li class="list-inline-item"><a href="">augmenté</a></li>
            </ul>
        </div>

        <div class="mid-header">

            <div class="logo-search">

                <div class="brand-area">
                    <div class="img-box"><img class="img-fluid" src="image/logo.svg" alt="logo HiTech"></div>
                    <div class="brand-text">
                        <p>HiTech.NET</p>
                        <p>Tout le matériel High-Tech</p>
                    </div>
                </div>

                <div class="search-area">
                    <div class="search-container">
                        <form method="get">
                            <input type="search" placeholder="Chercher un produit, une marque..." name="search" id="product-search" class="search-bar" />
                            <p>❯❯❯</p>
                            <select class="category-bar" name="product-category" id="product-category">
                                <option value="all-shelves">Tous les rayons...</option>
                                <option value="computers">Ordinateurs</option>
                                <option value="devices">Péripheriques & composants</option>
                                <option value="phones">Téléphones</option>
                                <option value="connected">Objets connectés</option>
                            </select>
                            <div class="loupe-box">
                                <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="user-area">
                <div class="user-box">
                    <i class="fa-regular fa-user"></i>
                    <a href="">Mon compte</a>
                </div>
                <div class="user-box">
                    <i class="fa-solid fa-cart-shopping"></i>
                    <a href="">Mon panier</a>
                </div>
            </div>

        </div>

        <div class="nav-area">
            <nav class="nav-bar">
                <div class="menu-box">
                    <i class="fa-solid fa-computer"></i>
                    <a href="">Ordinateurs</a>
                </div>
                <div class="menu-box">
                    <i class="fa-solid fa-database"></i>
                    <a href="">Péripheriques & composants</a>
                </div>
                <div class="menu-box">
                    <i class="fa-solid fa-mobile-screen"></i>
                    <a href="">Téléphones</a>
                </div>
                <div class="menu-box">
                    <i class="fa-solid fa-stopwatch"></i>
                    <a href="">Objets connectés</a>
                </div>
            </nav>
        </div>

    </div>
</header>