<main class="main-container">

    <div class="entete">
        <a href="#"><i class="fa-solid fa-shop"></i></a>
        <a href="#">Accueil</a>
        <p>❯</p>
        <a href="#"><i class="fa-solid fa-database"></i></a>
        <a href="#">Périphériques & composants</a>
        <p>❯</p>
        <a href="#">Ecrans d'ordinateur</a>
        <p>❯</p>
        <p>AOC 24B1XHS</p>
    </div>

    <div class="product-header">
        <h1>AOC 24B1XHS</h1>
        <div class="idlink-container">
            <a href="#presentation">Présentation</a>
            <a href="#descriptif">Descriptif</a>
            <a href="#perks">Caractéristiques techniques</a>
        </div>
    </div>

    <section id="presentation" class="product-presentation">
        <div class="line-bloc">
            <h2>Présentation</h2>
            <div class="dotted-line"></div>
        </div>

        <div class="tags">
            <a href="">1920 x 1080 pixels</a>
            <a href="">7 ms</a>
            <a href="">Format large 16/9</a>
            <a href="">Dalle IPS</a>
            <a href="">HDMI</a>
            <a href="">VGA</a>
            <a href="">Noir</a>
        </div>

        <article class="product-bloc">
            <div class="img-area">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="image/slide-1-lg.jpg" class="d-block w-100" alt="Ecran face avant">
                        </div>
                        <div class="carousel-item">
                            <img src="image/slide-2-lg.jpg" class="d-block w-100" alt="Ecran de biais 1">
                        </div>
                        <div class="carousel-item">
                            <img src="image/slide-3-lg.jpg" class="d-block w-100" alt="Ecran de biais 2">
                        </div>
                        <div class="carousel-item">
                            <img src="image/slide-4-lg.jpg" class="d-block w-100" alt="Ecran face arrière 1">
                        </div>
                        <div class="carousel-item">
                            <img src="image/slide-5-lg.jpg" class="d-block w-100" alt="Ecran face arrière 2">
                        </div>
                    </div>
                </div>
                <div class="all-img-container">
                    <p>Photos non contractuelles</p>
                    <div class="all-img">
                        <img src="image/slide-1-lg.jpg" class="img-screen" alt="Ecran face avant">
                        <img src="image/slide-2-lg.jpg" class="img-screen" alt="Ecran de biais 1">
                        <img src="image/slide-3-lg.jpg" class="img-screen" alt="Ecran de biais 2">
                        <img src="image/slide-4-lg.jpg" class="img-screen" alt="Ecran face arrière 1">
                        <img src="image/slide-5-lg.jpg" class="img-screen" alt="Ecran face arrière 2">
                    </div>
                </div>
            </div>
            <div class="product-description">
                <div class="marque-bloc">
                    <div class="img-box">
                        <img class="img-fluid logo-aoc" src="image/logo-lg.png" alt="Marque écran">
                    </div>
                    <p>Marque: AOC</p>
                </div>
                <div class="buy-bloc">
                    <div class="price-area">
                        <div class="price-text">
                            <p>109€94</p>
                            <p>dont éco-participation 1€70</p>
                        </div>
                        <div class="button-bloc">
                            <button class="add-button1">Ajouter au panier</button>
                            <button class="add-button2">Ajouter à ma liste d'envie</button>
                        </div>
                    </div>
                    <div class="garanty-bloc">
                        <p>Garantie: 2 années vendeur</p>
                    </div>
                </div>

                <div class="description-area">
                    <p>Un écran 23,8" Full HD et sans bords; c'est sûrement votre futur moniteur pour la maison ou le bureau. AOC vous propose le 24B1XHS, un produit élégant au look doté d'une dalle VA avec un temps de réponse rapide de 7 ms en résolution
                        1920 x 1080 pixels. Cet écran WLED très fonctionnel offre un contenu avec un fréquence de 60 Hz, idéal pour tous les usages du quotidien.</p>
                    <ul>
                        <li>Écran large de 23.8" avec résolution Full HD (1920 x 1080)</li>
                        <li>Des couleurs riches et nuancées avec un contraste dynamique de 20.000.000:1 (typique 1000:1)</li>
                        <li>Temps de réponse de 7 ms</li>
                        <li>Dalle IPS</li>
                        <li>Luminosité 250 cd/m²</li>
                        <li>Modes Flicker-Free et Anti-lumière bleue (Low blue mode)</li>
                        <li>Connecteurs : HDMI 1.4, VGA</li>
                        <li>Design sans contour & profil plat</li>
                        <li>Consommation d'énergie modeste : 25 Watts </li>
                        <li>Dimensions (avec support) : 419.8 x 540.1 x 186.8 mm</li>
                        <li>Poids : 2.48 kg</li>
                    </ul>
                </div>
            </div>
        </article>
    </section>

    <section id="descriptif" class="product-descriptif">
        <div class="line-bloc">
            <h2>Descriptif</h2>
            <div class="dotted-line"></div>
        </div>

        <article class="article1">
            <div class="line-bloc">
                <h2 class="h2size">Un moniteur Full HD performant et tout en finesse</h2>
                <div class="dotted-line"></div>
            </div>
            <div class="descriptif-container column-reverse">
                <div class="text-container">
                    <p>Issu de la série B1, le moniteur AOC 24B1XHS dispose de tous les atouts indispensables pour offrir une expérience utilisateur agréable. Son écran Full HD de 23.8" s'accompagne d'une dalle IPS ainsi que d'un temps de réponse de
                        7 ms pour une image toujours performante. Aussi, le 24B1XHS séduit par son profil plat et son design sans contour qui favorise le plaisir visuel et l'immersion. Ce moniteur WLED trouvera facilement une place de choix sur votre
                        bureau pour toutes vos utilisations quotidiennes.</p>
                </div>
                <div class="border-img">
                    <img class="img-fluid" src="image/screen.png" alt="Diagonale écran">
                </div>
            </div>
        </article>

        <article>
            <div class="line-bloc">
                <h2 class="h2size">Appréciez le design sans contour</h2>
                <div class="dotted-line"></div>
            </div>
            <div class="descriptif-container column">
                <div class="border-img">
                    <img class="img-fluid" src="image/desc-1.jpg" alt="Trois écrans">
                </div>
                <div class="text-container">
                    <p>En plus du look moderne et attrayant qu'il procure, le design sans contour permet des configurations à plusieurs écrans sans interruption. Votre curseur, vos fenêtres ne sont plus perdus dans les abysses sombres des contours lorsque
                        plusieurs écrans sont placés les uns à côté des autres.</p>
                    <p>Le profil plat de ce moniteur AOC offre de nombreux avantages. Très élégant sous tous les angles, il devient un choix idéal dans les espaces publics. Sa finesse et sa conception moderne lui permettent d'occuper moins de place sur
                        le bureau.</p>
                </div>
            </div>
        </article>

        <article>
            <div class="line-bloc">
                <h2 class="h2size">Tout le confort nécessaire</h2>
                <div class="dotted-line"></div>
            </div>
            <div class="descriptif-container column-reverse">
                <div class="text-container">
                    <p>Agréable visuellement et intuitif, ce moniteur dispose également d'une dalle IPS. Cette dernière reproduit des couleurs éclatantes et offre de très larges angles de vue. De cette façon, les images gardent toujours un excellent
                        aspect et une parfaite précision, quel que soit l'angle auquel vous regardez l'écran. </p>
                    <p>Vous voulez utiliser votre écran même dans un environnement très lumineux, à côté d'une fenêtre au soleil par exemple ? La haute luminosité de 250 cd/m² garantit une bonne visibilité, même dans des conditions difficiles.</p>
                </div>
                <div class="border-img">
                    <img class="img-fluid" src="image/desc-2.jpg" alt="Démonstration écran">
                </div>
            </div>
        </article>
    </section>

    <section id="perks" class="product-perks">
        <div class="line-bloc">
            <h2>Caractéristiques techniques</h2>
            <div class="dotted-line"></div>
        </div>

        <article class="perks-container">
            <h3>Affichage</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Taille de l'écran</td>
                        <td>23.8 pouces</td>
                    </tr>
                    <tr>
                        <td>Format de l'écran</td>
                        <td>16/9</td>
                    </tr>
                    <tr>
                        <td>Type de Dalle</td>
                        <td>Dalle IPS</td>
                    </tr>
                    <tr>
                        <td>Technologie LCD</td>
                        <td>IPS</td>
                    </tr>
                    <tr>
                        <td>Résolution Max</td>
                        <td>1920 x 1080 pixels</td>
                    </tr>
                    <tr>
                        <td>Dot Pitch</td>
                        <td>0.2745 mm</td>
                    </tr>
                    <tr>
                        <td>Luminosité</td>
                        <td>250 cd/m²</td>
                    </tr>
                    <tr>
                        <td>Contraste</td>
                        <td>20000000 /1</td>
                    </tr>
                    <tr>
                        <td>Temps de réponse</td>
                        <td>7 ms</td>
                    </tr>
                    <tr>
                        <td>Angle de vision (horizontal)</td>
                        <td>178 Degré(s)</td>
                    </tr>
                    <tr>
                        <td>Angle de vision (vertical)</td>
                        <td>178 Degré(s)</td>
                    </tr>
                    <tr>
                        <td>Dalle mate/antireflets</td>
                        <td>Oui</td>
                    </tr>
                    <tr>
                        <td>NVIDIA G-SYNC</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Adaptive-Sync</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>AMD FreeSync</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Flicker-Free</td>
                        <td>Oui</td>
                    </tr>
                    <tr>
                        <td>Anti-lumière bleue</td>
                        <td>Oui</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container">
            <h3>Ecran</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Type d'écran</td>
                        <td>LED</td>
                    </tr>
                    <tr>
                        <td>Ecran large</td>
                        <td>Oui</td>
                    </tr>
                    <tr>
                        <td>Ecran incurvé</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Borderless</td>
                        <td>Oui</td>
                    </tr>
                    <tr>
                        <td>Compatible 3D</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Ecran tactile</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Fréquence verticale mini</td>
                        <td>60 Hz</td>
                    </tr>
                    <tr>
                        <td>Type d'activités</td>
                        <td>Bureautique</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container">
            <h3>Ergonomie</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Pivot</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Pied réglable en hauteur</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Pied amovible</td>
                        <td>Oui</td>
                    </tr>
                    <tr>
                        <td>Fixation VESA</td>
                        <td>N/A</td>
                    </tr>
                    <tr>
                        <td>Angle inclinaison vers l'arrière (haut)</td>
                        <td>21.5 Degré(s)</td>
                    </tr>
                    <tr>
                        <td>Angle inclinaison vers l'avant (bas)</td>
                        <td>3.5 Deg</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container">
            <h3>Connectique</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Entrées vidéo</td>
                        <td>1 X HDMI Femelle, 1 X VGA (D-sub 15 Femelle)</td>
                    </tr>
                    <tr>
                        <td>Entrée audio</td>
                        <td>Aucun(e)</td>
                    </tr>
                    <tr>
                        <td>Sorties audio</td>
                        <td>1 X Line OUT (Jack 3.5mm Femelle)</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container">
            <h3>Multimédia</h3>
            <table>
                <tbody>
                    <tr>
                        <td>H.P. Intégrés</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Webcam</td>
                        <td>Non</td>
                    </tr>
                    <tr>
                        <td>Tuner TV</td>
                        <td>Non</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container">
            <h3>Caractéristiques physiques</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Couleur</td>
                        <td>Noir</td>
                    </tr>
                    <tr>
                        <td>Largeur</td>
                        <td>540.1 mm</td>
                    </tr>
                    <tr>
                        <td>Hauteur</td>
                        <td>417.4 mm</td>
                    </tr>
                    <tr>
                        <td>Profondeur</td>
                        <td>186.8 mm</td>
                    </tr>
                    <tr>
                        <td>Poids</td>
                        <td>2.48 kg</td>
                    </tr>
                    <tr>
                        <td>Pack multi-écrans</td>
                        <td>Non</td>
                    </tr>
                </tbody>
            </table>
        </article>

        <article class="perks-container last-pcontainer">
            <h3>Alimentation</h3>
            <table>
                <tbody>
                    <tr>
                        <td>Consommation</td>
                        <td>25 W</td>
                    </tr>
                    <tr>
                        <td>Consommation en veille</td>
                        <td>0.5 W</td>
                    </tr>
                    <tr>
                        <td>Alimentation interne</td>
                        <td>Non</td>
                    </tr>
                </tbody>
            </table>
        </article>
    </section>

</main>